sudo: false
language: php

php:
 - 5.3.3
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - nightly
 - hhvm

install:
 - composer install -n --prefer-source

before_script:
 - CODE_COVERAGE=`echo $TRAVIS_PHP_VERSION | grep -v "hhvm" | wc -l`

script:
 - if [ "$CODE_COVERAGE" = "1" ]; then php vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.clover; else php vendor/bin/phpunit --verbose; fi

after_script:
 - if [ "$CODE_COVERAGE" = "1" ]; then wget "https://scrutinizer-ci.com/ocular.phar"; fi
 - if [ "$CODE_COVERAGE" = "1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

matrix:
 fast_finish: true
 allow_failures:
  - php: nightly

notifications:
 email: false

